name: rede_social
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  camera: ^0.10.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env